### ISSUE TITLE
[Question] unreproducible double-dot syntax example on README

### ISSUE THREAD

**Issue by fummicc1** [pointfreeco/swift-case-paths#119]
Hello, I am new to swift-case-paths and reading [README.md](https://github.com/pointfreeco/swift-case-paths).

regarding section [Case paths vs. key paths](https://github.com/pointfreeco/swift-case-paths#case-paths-vs-key-paths), I would like you to conform my usage is correct or not, because I can't use double-dot syntax to dive into deeper enum case.

> Case paths, like key paths, compose. Where key paths use dot-syntax to dive deeper into a structure, case paths use a double-dot syntax:
> ```swift
> \HighScore.user.name
> // WritableKeyPath<HighScore, String>
> 
> /Result<Authentication, Error>..Authentication.authenticated
> // CasePath<Result<Authentication, Error>, String>
> ```
> 

here is my code trying above syntax.

```swift
import CasePaths
import Foundation

enum Selection: String {
    case alice
    case bob
}

/**
 To dive into a structure, keyPath uses dot (`.`) syntax, but case-paths uses double-dot (`..`) syntax.
 */
func example02() {
    /Result<Selection, Error>..Selection.alice

}
```

<img width="800" alt="Screenshot 2023-10-22 at 17 24 54" src="https://github.com/pointfreeco/swift-case-paths/assets/44002126/db1a1d5a-0373-4d36-99f4-356035eb7392">

instead, I could use below way but I would like to check if README is old or not.

```swift
import CasePaths
import Foundation

enum Selection: String {
    case alice
    case bob
}

/**
 To dive into a structure, keyPath uses dot (`.`) syntax, but case-paths uses double-dot (`..`) syntax.
 */
func example02() {
    /Result<Selection, Error>.success(.alice)
}
```

**Comment by stephencelis** [comment]
@fummicc1 Sorry for the confusion, the `..` operator requires parenthesizing of the path, or spaces around it for the compiler to parse things correctly.

```swift
/Result<Selection, Error>.success .. Selection.alice
```

I've updated the README, but also we plan to address some shortcomings of the current operator in the near future. Stay tuned!
