### ISSUE TITLE
Equatable CasePath

### ISSUE THREAD

**Issue by mycroftcanner** [pointfreeco/swift-case-paths#16]
Is it possible to make CasePath Equatable?

**Comment by stephencelis** [comment]
Unfortunately not. While it would be possible to add an `identifier` field to equate against, it'd be a breaking change and there's no way as far as I can tell to automatically derive an identifier from an enum case embed function. Open to ideas! But it might not be possible and all the more reason to introduce case paths at the language level so they can be hashable like key paths.

Alternatively, you could wrap case paths in a type that _is_ equatable by providing the strategy for comparing paths. Not ideal, but could unblock you.

**Comment by stephencelis** [comment]
I'm going to move this to be a discussion since it's not a bug, but is something that would be nice to solve (along with hashability), if anyone figures out how to do this!
