### ISSUE TITLE
@CasePathable triggers compiler bug with Never payloads

### ISSUE THREAD

**Issue by jshier** [pointfreeco/swift-case-paths#161]
Starting in 1.4.0, enums with `Never` associated values, even as part of a generic type, trigger some sort of compiler bug (or misleading diagnostic) where it thinks switches on the enum may have unknown values. For example:

```swift
@CasePathable
enum Action {
    case alert(Never)
}
```

produces the warning `Switch covers known cases, but 'Action' may have additional unknown values` in its generated code. More specifically:

```swift
public struct AllCasePaths: Sequence {
    public subscript(root: Action) -> PartialCaseKeyPath<Action> {
        switch root { // Warning produced here.
        case .alert:
            return \.alert
        }
    }
}
```

This enum compiles cleanly if any other type is used as an associated value.

**Environment**
  - swift-case-paths: 1.4.0 && 1.4.1
  - Xcode: 15.4
  - Swift: 5.10

Edited to simplify example.

**Comment by jshier** [comment]
I can't reproduce the `Never` in generics case outside of a TCA example:

```swift
@CasePathable
enum Action {
    case alert1(Feature2.Action)
    case alert2(AlertState<Never> .Action)
}

@Reducer
struct Feature2 {}
```

This produces the same warning. If I use my own generic type, even with a child type, it doesn't warn.

**Comment by jshier** [comment]
Perhaps the issue is related to the fact that a `PartialCasePath<Never>` can't be instantiated?

**Comment by stephencelis** [comment]
Thanks for the report! Luckily we can work around it by ditching the `switch` and leveraging `CasePathable.is`, but the warning is strange and I'm not sure if a bug should be filed with Apple.

**Comment by stephencelis** [comment]
@jshier Since this is just producing a warning, we'll probably not cut a release immediately after merging, and instead let the dust settle on the 1.4 release a little longer just in case there are other issues lurking.
