### ISSUE TITLE
Memory leak when using nested structs

### ISSUE THREAD

**Issue by rjantz2** [pointfreeco/swift-case-paths#19]
To replicate build and profile the attached project.

Interestingly enough it doesn't leak memory if either or both of the properties are changed from `string` to `int`

[MemoryLeakTest.zip](https://github.com/pointfreeco/swift-case-paths/files/5876734/MemoryLeakTest.zip)

**Comment by pteasima** [comment]
Thanks for submitting this Ryan.

I was in on debugging this. I should say that leaks are found with the Leaks profiler from Instruments. We don't know exactly what is leaking and dont know how to write a failing test case. However, the profiler leads to this line https://github.com/pointfreeco/swift-case-paths/blob/469ef5103670d65f554f494ce9b6a46e0ec286db/Sources/CasePaths/EnumReflection.swift#L61 and it wont leak if we dont use `/` (implement `embed` and `extract` manually). We're both happy to PR if you can guide us towards a fix.

**Comment by rjantz2** [comment]
@pteasima The credit for narrowing it down to this is yours as you well know! Thank you for adding these bits I forgot.

**Comment by pteasima** [comment]
> @pteasima The credit for narrowing it down to this is yours as you well know! Thank you for adding these bits I forgot.

Haha definitelly not seeking credit 😅 just checked the thread out of interest.

**Comment by mbrandonw** [comment]
Hey @rjantz2 and @pteasima, good find! This was very bizarre, but @stephencelis and I tracked it down to what appears to be a bug with Swift and `Mirror`. We've got a fix here: https://github.com/pointfreeco/swift-case-paths/pull/20.
