### ISSUE TITLE
Should I make a PR? 😅

### ISSUE THREAD

**Issue by maximkrouk** [pointfreeco/swift-case-paths#27]
I'm using a type, called `CasePathValueDetector` which can detect if the case is an expected case, but it erases the Value type from CasePath to enable me to use arrays of CasePath for cases with different associated values
```swift
public struct CasePathValueDetector<Root> {
  private let _detect: (Root) -> Bool
  
  public func `is`(_ action: Root) -> Bool {
    _detect(action)
  }
  
  public static func detector<Value>(for casePath: CasePath<Root, Value>) -> CasePathValueDetector {
    CasePathValueDetector(_detect: { casePath.extract(from: $0) == nil })
  }
}

public prefix func / <Root, Value>(
  embed: @escaping (Value) -> Root
) -> CasePathValueDetector<Root> {
  .detector(for: /embed)
}

public prefix func / <Root>(
  case: Root
) -> CasePathValueDetector<Root> {
  .detector(for: /`case`)
}
```
with TCA to enable `dismissOn` higher order reducer for handling modals in UIKit (but it may usefull for creating generalized `.on(_ action: Action, _ reduce: (inout State, Action, Environment) -> Effect) -> Reducer` reducer for example)
```swift
public let invitationModalReducer = Reducer<
  Modal<InvitationState>,
  ModalAction<InvitationAction>,
  InvitationEnvironment
>.combine(
  Reducer.modal(
    invitationReducer,
    state: \.self,
    action: /.self,
    environment: { $0 }
  )
  .dismissOn(
    /InvitationAction.confirmChoice,
    /InvitationAction.close
  )
)
```
it does the same as
```swift
public let quizModalReducer = Reducer<
  Modal<QuizState>,
  ModalAction<QuizAction>,
  QuizEnvironment
>.combine(
  Reducer.modal(
    quizReducer,
    state: \.self,
    action: /.self,
    environment: { $0 }
  )
  .lifecycleBasedRouting(/QuizAction.lifecycle)
  .dismissOn(.exit, .timeout, .interactiveTimeout)
}
```
but the second example has no associated values so I can just pass enum cases.

Method's signatures are
```swift
extension Reducer {
  public func dismissOn<LocalAction>(_ actions: LocalAction...) -> Reducer
  where Action == ModalAction<LocalAction>, LocalAction: Equatable { ... }

  public func dismissOn<LocalAction>(_ paths: CasePathValueDetector<LocalAction>...) -> Reducer
  where Action == ModalAction<LocalAction>, LocalAction: Equatable { ... }
}

**Comment by maximkrouk** [comment]
Maybe you have a better idea for naming 🌚

Implementation of `dismissOn` method for `CasePathValueDetector` is
```swift
extension Reducer {
  public func presentOn<LocalAction>(_ detectors: CasePathValueDetector<LocalAction>...) -> Reducer
  where Action == ModalAction<LocalAction>, LocalAction: Equatable {
    .combine(
      self,
      Reducer { state, action, environment in
        guard case let .action(action) = action else { return .none}
        for detector in detectors where detector.marker(for: action).hasValue {
          return .value(.present)
        }
        return .none
      }
    )
  }
}
```

**Comment by maximkrouk** [comment]
Maybe adding `AnyCasePath` and `PartialCasePath` will be closer to the `KeyPath` API, but I decided to fix local problem with a minimal solution without erasing type to Any, but with just hiding the logic into a function, so I probably can just write `AnyCasePath` and `PartialCasePath` implementations if needed

**Comment by stephencelis** [comment]
`PartialCasePath` was the first thing that came to mind when I saw your original post :smile: I think such a thing could definitely be useful, but it would require us to reconsider things (`CasePath` is a simple struct, but `KeyPath` is a class hierarchy). Thanks for bringing this up!

In the meantime we think ad hoc code like you've written in `dismissOn` is totally cool!

**Comment by maximkrouk** [comment]
At first, I thought it would be possible to implement using protocols (like `AnyCasePath`), but this implementation won't allow us to keep KeyPath API, because we won't be able to treat `CasePath` as `PartialCasePath` etc, so classes would be required...
Plus the API, in general, will be reconsidered for things like `CasePath` & `WritableCasePath` if this separation is needed (maybe even not, also it will lead to major API changes if implemented), so there is definitely some stuff to think about 🤔

**Comment by maximkrouk** [comment]
Also `PartialCasePath` may be just a simple typealias to `CasePath<Root, Any>` and `AnyCasePath` will be `CasePath<Any, Any>`, the only thing will left to implement is a few `/` operators...

_P.S. Maybe consider moving this issue to Discussions tab, I guess that place will fit sharing ideas more_ 🙂
