### ISSUE TITLE
EXC_BAD_ACCESS when extracting a `Result.success` from a failure, if the result is `Result<_, Error>`

### ISSUE THREAD

**Issue by klundberg** [pointfreeco/swift-case-paths#53]
This happens in 0.7.0, I haven't tried other releases.

I've encountered this crash in the wild, which I had to work around by not using case paths for any `Result` where the `Failure` generic type is `Error`. If you try to add this unit test to the test suite in this repo, you can reproduce it:

```swift
  func testExtractSuccessFromFailedResultWithErrorProtocolError() throws {
    struct MyError: Error {}
    let x = Result<String, Error>.failure(MyError()) 

    // since it's `Error`, execution traps at the following line with an EXC_BAD_ACCESS. 
    // If the  result type was over `MyError`, it would work correctly.
    XCTAssertNil((/Result.success).extract(from: x))
  }
```

There must be some swift runtime issue with Error protocol types vs concrete types that conform to `Error`, since it works if the type is `Result<String, MyError>` instead. I'm not too well versed in the swift runtime details to know how to fix this, except to work around it by not using case paths for these kinds of `Result` types for now.

If the value was a `.success` instead of a `.failure`, extraction does not crash, only when trying to extract a `.success` from this specific kind of Result if the value is a `.failure`. Extracting a `.failure` from this value also seems to work as expected.

**Comment by mbrandonw** [comment]
Oof, the `Error` type has given us a lot of troubles with Swift runtime metadata 🙁. We'll investigate a workaround.

@mayoff perhaps you've got some ideas too?

**Comment by mayoff** [comment]
I found [the following comment](https://github.com/apple/swift/blob/7123d2614b5f222d03b3762cb110d27a9dd98e24/include/swift/Runtime/Error.h#L15-L19) in the Swift repo:

> ```c++
> // The ABI here is quite different in ObjC and non-ObjC modes.
> // In ObjC mode, SwiftError is closely related to the NSError class:
> // native errors are boxed as a subclass of NSError, but non-native
> // errors may simply be NSError objects directly from Objective-C.
> // In non-ObjC mode, SwiftError boxes are always native.
>```

Translation:

- A “native error” means a type (defined in Swift) that conforms to the `Error` protocol.

- On non-Apple platforms (which do not support Objective-C interoperability), an `Error` existential is stored like any other protocol existential, in a four-word “box” (a `TargetOpaqueExistentialContainer` in the C++ runtime source ode).

- On Apple platforms (which support Objective-C interoperability), an `Error` existential is a one-word pointer to an object which can act like (sometimes genuinely is) an `NSError` or subclass thereof.

However, `Strategy` doesn't know about this special treatment. It just detects that the value is some sort of protocol existential and treats it as such.

I will teach `Strategy` about this special case.
