### ISSUE TITLE
EXC_BAD_ACCESS extracting existensial

### ISSUE THREAD

**Issue by kmcbride** [pointfreeco/swift-case-paths#63]
This was partially solved in https://github.com/pointfreeco/swift-case-paths/issues/53 but it seems that the fix is needed for all object-bound existential types.

Here's a rudimentary case that reproduces the crash (tested with Xcode 13.1, iOS 13.5 simulator):
```swift
private protocol TestObjectProtocol: AnyObject {}

func testObjectBoundExistensialPayload() {
  class Class: TestObjectProtocol {}
  enum Enum {
    case int(Int)
    case objectBoundExistensial(TestObjectProtocol)
  }
  let intPath = /Enum.int
  let object = Class()
  for _ in 1...2 {
      XCTAssertNil(intPath.extract(from: .objectBoundExistensial(object)))
  }
}
```

**Comment by stephencelis** [comment]
This is tricky 😕

@mayoff may have an idea of how to get it working, but I can't seem to figure out the appropriate dynamic check, or where the runtime exposes this information.

**Comment by stephencelis** [comment]
In the meantime, you can also work around this problem by introducing a concrete wrapper. This gets the test passing:

```swift
  func testObjectBoundExistentialPayload() {
    class Class: TestObjectProtocol {}
    struct Wrapper { var rawValue: TestObjectProtocol }
    enum Enum {
      case int(Int)
      case objectBoundExistential(Wrapper)
    }
    let intPath = /Enum.int
    let object = Class()
    for _ in 1...2 {
      XCTAssertNil(intPath.extract(from: .objectBoundExistential(Wrapper(rawValue: object))))
    }
  }
```

**Comment by iampatbrown** [comment]
Added #65 as a possible fix. Wouldn't mind waiting for @mayoff to chime in as well though. He may have an alternate solution.

**Comment by mayoff** [comment]
Looks reasonable to me. Thanks for not making me fix it. 😅

**Comment by iampatbrown** [comment]
> Thanks for not making me fix it. 😅

Hahaha. No worries 😛
