### ISSUE TITLE
Documentation links 404

### ISSUE THREAD

**Issue by jshier** [pointfreeco/swift-case-paths#70]
While the link to the documentation itself works, from within the documentation everything 404s. For instance, this is the link to the [`..` operator](https://pointfreeco.github.io/swift-case-paths/__).

**Comment by mbrandonw** [comment]
Dang, thanks for letting us know. For me it seems only the operators 404. I get correct links for the other symbols, such as [`extract`](https://pointfreeco.github.io/swift-case-paths/extract(case_from_)/).

We are slowly moving everything over to DocC (have done so for TCA and parsing), so I think this will be our next one to do.

**Comment by jshier** [comment]
You're right, only the operators 404. I only clicked the one upper function, the one for `..`.

**Comment by mbrandonw** [comment]
Weirdly swift-doc isn't even picking up the methods on `CasePath`, such as `modify` and `appending`. All the more reason to switch over to DocC soon.

**Comment by mbrandonw** [comment]
Oh never mind, all the methods are under the `CasePath` page. I'm conflating how DocC and swift-doc work.

**Comment by stephencelis** [comment]
Fixed by migrating to DocC! https://pointfreeco.github.io/swift-case-paths/main/documentation/casepaths/
